// Generated by gencpp from file calibration/GetJointPositionsRequest.msg
// DO NOT EDIT!


#ifndef CALIBRATION_MESSAGE_GETJOINTPOSITIONSREQUEST_H
#define CALIBRATION_MESSAGE_GETJOINTPOSITIONSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace calibration
{
template <class ContainerAllocator>
struct GetJointPositionsRequest_
{
  typedef GetJointPositionsRequest_<ContainerAllocator> Type;

  GetJointPositionsRequest_()
    {
    }
  GetJointPositionsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::calibration::GetJointPositionsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::calibration::GetJointPositionsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetJointPositionsRequest_

typedef ::calibration::GetJointPositionsRequest_<std::allocator<void> > GetJointPositionsRequest;

typedef boost::shared_ptr< ::calibration::GetJointPositionsRequest > GetJointPositionsRequestPtr;
typedef boost::shared_ptr< ::calibration::GetJointPositionsRequest const> GetJointPositionsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::calibration::GetJointPositionsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::calibration::GetJointPositionsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace calibration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::calibration::GetJointPositionsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calibration::GetJointPositionsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calibration::GetJointPositionsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calibration::GetJointPositionsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration::GetJointPositionsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration::GetJointPositionsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::calibration::GetJointPositionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::calibration::GetJointPositionsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::calibration::GetJointPositionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calibration/GetJointPositionsRequest";
  }

  static const char* value(const ::calibration::GetJointPositionsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::calibration::GetJointPositionsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::calibration::GetJointPositionsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::calibration::GetJointPositionsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetJointPositionsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::calibration::GetJointPositionsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::calibration::GetJointPositionsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CALIBRATION_MESSAGE_GETJOINTPOSITIONSREQUEST_H
