(cl:defpackage calibration-srv
  (:use )
  (:export
   "GETJOINTPOSITIONS"
   "<GETJOINTPOSITIONS-REQUEST>"
   "GETJOINTPOSITIONS-REQUEST"
   "<GETJOINTPOSITIONS-RESPONSE>"
   "GETJOINTPOSITIONS-RESPONSE"
   "SETJOINTPOSITIONS"
   "<SETJOINTPOSITIONS-REQUEST>"
   "SETJOINTPOSITIONS-REQUEST"
   "<SETJOINTPOSITIONS-RESPONSE>"
   "SETJOINTPOSITIONS-RESPONSE"
  ))

