// Generated by gencpp from file calibration/GetJointPositionsResponse.msg
// DO NOT EDIT!


#ifndef CALIBRATION_MESSAGE_GETJOINTPOSITIONSRESPONSE_H
#define CALIBRATION_MESSAGE_GETJOINTPOSITIONSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace calibration
{
template <class ContainerAllocator>
struct GetJointPositionsResponse_
{
  typedef GetJointPositionsResponse_<ContainerAllocator> Type;

  GetJointPositionsResponse_()
    : joint_positions()  {
    }
  GetJointPositionsResponse_(const ContainerAllocator& _alloc)
    : joint_positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_positions_type;
  _joint_positions_type joint_positions;





  typedef boost::shared_ptr< ::calibration::GetJointPositionsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::calibration::GetJointPositionsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetJointPositionsResponse_

typedef ::calibration::GetJointPositionsResponse_<std::allocator<void> > GetJointPositionsResponse;

typedef boost::shared_ptr< ::calibration::GetJointPositionsResponse > GetJointPositionsResponsePtr;
typedef boost::shared_ptr< ::calibration::GetJointPositionsResponse const> GetJointPositionsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::calibration::GetJointPositionsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::calibration::GetJointPositionsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace calibration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::calibration::GetJointPositionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calibration::GetJointPositionsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calibration::GetJointPositionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calibration::GetJointPositionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration::GetJointPositionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration::GetJointPositionsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::calibration::GetJointPositionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a286ff40b196573b9ebf3999a2f8d438";
  }

  static const char* value(const ::calibration::GetJointPositionsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa286ff40b196573bULL;
  static const uint64_t static_value2 = 0x9ebf3999a2f8d438ULL;
};

template<class ContainerAllocator>
struct DataType< ::calibration::GetJointPositionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calibration/GetJointPositionsResponse";
  }

  static const char* value(const ::calibration::GetJointPositionsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::calibration::GetJointPositionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_positions\n\
\n\
";
  }

  static const char* value(const ::calibration::GetJointPositionsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::calibration::GetJointPositionsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetJointPositionsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::calibration::GetJointPositionsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::calibration::GetJointPositionsResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint_positions[]" << std::endl;
    for (size_t i = 0; i < v.joint_positions.size(); ++i)
    {
      s << indent << "  joint_positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CALIBRATION_MESSAGE_GETJOINTPOSITIONSRESPONSE_H
