// Generated by gencpp from file calibration/SetJointPositions.msg
// DO NOT EDIT!


#ifndef CALIBRATION_MESSAGE_SETJOINTPOSITIONS_H
#define CALIBRATION_MESSAGE_SETJOINTPOSITIONS_H

#include <ros/service_traits.h>


#include <calibration/SetJointPositionsRequest.h>
#include <calibration/SetJointPositionsResponse.h>


namespace calibration
{

struct SetJointPositions
{

typedef SetJointPositionsRequest Request;
typedef SetJointPositionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointPositions
} // namespace calibration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::calibration::SetJointPositions > {
  static const char* value()
  {
    return "702c3dade1da9e295e178fcc32cce64f";
  }

  static const char* value(const ::calibration::SetJointPositions&) { return value(); }
};

template<>
struct DataType< ::calibration::SetJointPositions > {
  static const char* value()
  {
    return "calibration/SetJointPositions";
  }

  static const char* value(const ::calibration::SetJointPositions&) { return value(); }
};


// service_traits::MD5Sum< ::calibration::SetJointPositionsRequest> should match 
// service_traits::MD5Sum< ::calibration::SetJointPositions > 
template<>
struct MD5Sum< ::calibration::SetJointPositionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::calibration::SetJointPositions >::value();
  }
  static const char* value(const ::calibration::SetJointPositionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::calibration::SetJointPositionsRequest> should match 
// service_traits::DataType< ::calibration::SetJointPositions > 
template<>
struct DataType< ::calibration::SetJointPositionsRequest>
{
  static const char* value()
  {
    return DataType< ::calibration::SetJointPositions >::value();
  }
  static const char* value(const ::calibration::SetJointPositionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::calibration::SetJointPositionsResponse> should match 
// service_traits::MD5Sum< ::calibration::SetJointPositions > 
template<>
struct MD5Sum< ::calibration::SetJointPositionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::calibration::SetJointPositions >::value();
  }
  static const char* value(const ::calibration::SetJointPositionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::calibration::SetJointPositionsResponse> should match 
// service_traits::DataType< ::calibration::SetJointPositions > 
template<>
struct DataType< ::calibration::SetJointPositionsResponse>
{
  static const char* value()
  {
    return DataType< ::calibration::SetJointPositions >::value();
  }
  static const char* value(const ::calibration::SetJointPositionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CALIBRATION_MESSAGE_SETJOINTPOSITIONS_H
